DROP SCHEMA IF EXISTS CookeBook;
CREATE SCHEMA CookeBook;
USE CookeBook;

CREATE TABLE IF NOT EXISTS user(
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    login CHARACTER VARYING(50)
);

CREATE TABLE IF NOT EXISTS ingredient(
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS instruction(
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS pantry(
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS recipe(
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL
);